version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/supervise-calib:master_master-unstable_sources
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/root/.Xauthority:rw"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "/dev:/dev"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true



services:

#------------------------------------------------------------------------------------------------
  #Opening we open the viewer to see the raw left camera
  yview_left:
    <<: *yarp-base
    command: yarpview --name /viewer/left --x 635 --y 0

  #Opening we open the viewer to see the raw right camera
  yview_right:
    <<: *yarp-base
    command: yarpview --name /viewer/right --x 940 --y 0

  #Opening the viewer to see the display of calibSupervisor
  yview_calib_display:
    <<: *yarp-base
    command: yarpview --name /display --x 0 --y 0 --w 550 --h 550

  #Opening we open the viewer to see the left output of camCalib after calibration
  yview_camcalib_left:
    <<: *yarp-base
    command: yarpview --name /viewer_calib/left --x 635 --y 400

  #Opening we open the viewer to see the right output of camCalib after calibration
  yview_camcalib_right:
    <<: *yarp-base
    command: yarpview --name /viewer_calib/right --x 940 --y 400

  #Opening we open the viewer to see the template during calibration
  yview_template:
    <<: *yarp-base
    command: yarpview --name /viewer_template --x 0 --y 650 --w 450 --h 450

