version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/supervise-calib:master_master-unstable_sources
  environment:
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
    - APPSAWAY_CALIB_CONTEXT
    - ICUB_EYES_PATH
    - CAMERA_TYPES
    - RESOLUTIONS
    - MONO_CALIB
  volumes:
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "${APPSAWAY_CALIB_CONTEXT}:/usr/local/share/iCub/contexts/cameraCalibration/:rw"
    - "${APPSAWAY_CALIB_CONTEXT}/icubEyes.ini:/usr/local/share/ICUBcontrib/robots/${YARP_ROBOT_NAME}/icubEyes.ini:rw"
    - "${ICUB_EYES_PATH:-/dev/null}:/usr/local/share/iCub/contexts/cameraCalibration/customEyes.ini:rw"
  networks:
    - hostnet

#note: following services that need yarpRobotinterface is running, I write yarp wait /yarpRobotInterface;
#just to remember us to solve thi issue. Such yarp port doesn't exist.

services:
#following service are configured in icub-main/app/iCubStartup/scripts/iCubStartup.xml.template
  yserver:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp where | grep 'is available at ip' > /dev/null ; if [ ! $$? -eq 0 ]; then yarpserver --write; fi"

#------------------------------------------------------------------------------------------------
  #Modules
  yCalibSupervisor:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /viewer_template; if [ ${MONO_CALIB} = false ]; then if [ ${CAMERA_TYPES} = "Event-driven" ]; then calibSupervisor --file calibrations_event_304x240.ini --eventCam true --percentageThresh 86.0; else if [ ${RESOLUTIONS} = "320x240" ]; then calibSupervisor; else if [ ${RESOLUTIONS} = "640x480" ]; then calibSupervisor --file calibrations_rgb_640x480.ini; else if [ ${RESOLUTIONS} = "1024x768" ]; then calibSupervisor --file calibrations_rgb_1024x768.ini; fi; fi; fi; fi; else if [ ${CAMERA_TYPES} = "Event-driven" ]; then calibSupervisor --file calibrations_event_304x240.ini --eventCam true --stereo false --percentageThresh 86.0; else if [ ${RESOLUTIONS} = "320x240" ]; then calibSupervisor --stereo false; else if [ ${RESOLUTIONS} = "640x480" ]; then calibSupervisor --file calibrations_rgb_640x480.ini --stereo false; else if [ ${RESOLUTIONS} = "1024x768" ]; then calibSupervisor --file calibrations_rgb_1024x768.ini --stereo false; fi; fi; fi; fi; fi;"

  yUpdateFile:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /calibSupervisor/imageLeft:o ; if [ ! -z ${ICUB_EYES_PATH} ]; then run-all.sh /usr/local/share/iCub/contexts/cameraCalibration/customEyes.ini outputCalib.ini cameraCalibration $MONO_CALIB; else run-all.sh icubEyes.ini outputCalib.ini cameraCalibration $MONO_CALIB; fi"

  yStartCalib:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /stereoCalib/cmd; echo "start" | yarp rpc /stereoCalib/cmd"

#------------------------------------------------------------------------------------------------
  #Connections to the ports of the modules 

  yConnectToLeftRaw:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp wait /vFramer/left/image:o; else yarp wait /icub/cam/left; fi; yarp wait /viewer/left ; if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp connect /vFramer/left/image:o /viewer/left fast_tcp; else yarp connect /icub/cam/left /viewer/left fast_tcp; fi;"

  yConnectToRightRaw:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp wait /vFramer/right/image:o; else yarp wait /icub/cam/right; fi; yarp wait /viewer/right ; if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp connect /vFramer/right/image:o /viewer/right fast_tcp; else yarp connect /icub/cam/right /viewer/right fast_tcp; fi;"

  yConnectToLeftInImage:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp wait /vFramer/left/image:o; else yarp wait /icub/cam/left; fi; yarp wait /calibSupervisor/imageLeft:i ; if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp connect /vFramer/left/image:o /calibSupervisor/imageLeft:i fast_tcp; else yarp connect /icub/cam/left /calibSupervisor/imageLeft:i fast_tcp; fi;"


  yConnectToRightInImage:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp wait /vFramer/right/image:o; else yarp wait /icub/cam/right; fi; yarp wait /calibSupervisor/imageRight:i ; if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp connect /vFramer/right/image:o; /calibSupervisor/imageRight:i fast_tcp; else yarp connect /icub/cam/right /calibSupervisor/imageRight:i fast_tcp; fi;"

  yConnectToLeftStereoCalib:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /calibSupervisor/imageLeft:o ; yarp wait /stereoCalib/cam/left:i; yarp connect /calibSupervisor/imageLeft:o /stereoCalib/cam/left:i fast_tcp ;"

  yConnectToRightStereoCalib:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /calibSupervisor/imageRight:o ; yarp wait /stereoCalib/cam/right:i; yarp connect /calibSupervisor/imageRight:o /stereoCalib/cam/right:i fast_tcp ;"
  
  yConnectToDisplay:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /calibSupervisor/display:o ; yarp wait /display; yarp connect  /calibSupervisor/display:o /display fast_tcp;"

  #yConnectToViewerCalib:
  #  <<: *yarp-base
  #  deploy:
  #    placement:
  #      constraints: [node.labels.type != head]
  #    restart_policy:
  #      condition: on-failure
  #  command: sh -c "yarp wait /calibSupervisor/imageLeft:o ; yarp wait /sendtocalib; yarp connect /calibSupervisor/imageLeft:o /sendtocalib fast_tcp ;"

  yConnectToLeftInCamCalib:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp wait /vFramer/left/image:o; else yarp wait /icub/cam/left ; fi; yarp wait /camCalib/left/in; if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp connect /vFramer/left/image:o /camCalib/left/in fast_tcp ; else yarp connect /icub/cam/left /camCalib/left/in fast_tcp ; fi;"
  
  yConnectToRightInCamCalib:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp wait /vFramer/right/image:o; else yarp wait /icub/cam/right ; fi; yarp wait /camCalib/right/in; if [ ${CAMERA_TYPES} = "Event-driven" ]; then yarp connect /vFramer/right/image:o /camCalib/right/in fast_tcp ; else yarp connect /icub/cam/right /camCalib/right/in fast_tcp ; fi;"

  yConnectToLeftOutCamCalib:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /camCalib/left/out ; yarp wait /viewer_calib/left; yarp connect /camCalib/left/out /viewer_calib/left fast_tcp ;"
  
  yConnectToRightOutCamCalib:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /camCalib/right/out ; yarp wait /viewer_calib/right; yarp connect /camCalib/right/out /viewer_calib/right fast_tcp ;"

  yConnectToTemplate:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp wait /calibSupervisor/template:o ; yarp wait /viewer_template; yarp connect /calibSupervisor/template:o /viewer_template fast_tcp ;"
    
 #------------------------------------------------------------------------------------------------

  #use network.peer ip address and port 8080 to see the containers status in browser
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


networks:
  hostnet:
    external: true
    name: host

