version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/speech:v2020.08.patch-01_master-unstable_sources
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - FILE_INPUT
    - INPUT_BOX
    - GOOGLE_INPUT
    - LANGUAGE_INPUT
    - GOOGLE_PROCESSING
    - GOOGLE_SYNTHESIS_INPUT
    - LANGUAGE_SYNTHESIS_INPUT
    - VOICE_NAME_INPUT
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/root/.Xauthority:rw"
    - "${YARP_CONF_PATH}:/root/.config/yarp"
    - "${FILE_INPUT_PATH}:/root/authorization"
  networks:
    - hostnet

#note: following services that need yarpRobotinterface is running, I write yarp wait /yarpRobotInterface;
#just to remember us to solve thi issue. Such yarp port doesn't exist.

services:
#following service are configured in icub-main/app/iCubStartup/scripts/iCubStartup.xml.template
  yserver:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    command: sh -c "yarp where | grep 'is available at ip' > /dev/null ; if [ ! $$? -eq 0 ]; then yarpserver --write; fi"
  
#------------------------------------------------------------------------------------------------
  yDemoGoogleSpeech:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
    command: sh -c "if [ ${GOOGLE_INPUT} = 'True' ]; then yarp wait /microphone/audio:o; googleSpeech --language_code ${LANGUAGE_INPUT}; fi" 
 
  yDemoGoogleProcessing:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.labels.type != head]
    command: sh -c "if [ ${GOOGLE_PROCESSING} = 'True' ]; then yarp wait /microphone/audio:o; googleSpeechProcess; fi"

#now we connect the output of the googleSpeech to the process

  yConnectToGoogleSpeechProcess:
      <<: *yarp-base
      deploy:
        placement:
          constraints: [node.labels.type != head]
        restart_policy:
          condition: on-failure
      command: sh -c "if [ ${GOOGLE_PROCESSING} = 'True' ]; then if [ ${GOOGLE_INPUT} = 'True' ]; then yarp wait /googleSpeech/result:o; yarp wait /googleSpeechProcess/text:i; yarp connect /googleSpeech/result:o /googleSpeechProcess/text:i; fi; fi;"

  yconnect_audio:
    <<: *yarp-base
    container_name: yconnect_audio
    deploy:
      restart_policy:
        condition: on-failure
    command: sh -c "if [ ${GOOGLE_INPUT} = 'True' ]; then yarp wait /microphone/audio:o; yarp wait /googleSpeech/sound:i; yarp connect /microphone/audio:o /googleSpeech/sound:i tcp; fi;"

  yconnect_rpc:
    <<: *yarp-base
    container_name: yconnect_rpc
    deploy:
      restart_policy:
        condition: on-failure
    command: sh -c "if [ ${GOOGLE_INPUT} = 'True' ]; then yarp wait /microphone/rpc; yarp wait /googleSpeech/commands:rpc; yarp connect /googleSpeech/commands:rpc /microphone/rpc tcp; fi;"



#------------------------------------------------------------------------------------------------

  #use network.peer ip address and port 8080 to see the containers status in browser
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


networks:
  hostnet:
    external: true
    name: host

