version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/superbuild:devel_prod
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/root/.Xauthority:rw"
    - type: volume
      source: mystack_yarp-config
      target: /root/.config/yarp
      volume:
        nocopy: true
  network_mode: "host"
  privileged: true
  #ipc: host

services:
  #following service are configured in icub-main/app/iCubStartup/scripts/iCubStartup.xml.template
  gazebo:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.role == manager]
    command: gazebo


volumes:
  mystack_yarp-config:
    external: true