version: "3.7"

x-yarp-blender: &yarp-blender
  image: icubteamcode/blender:v2021.11.1_master_sources
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "/dev:/dev"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true

x-yarp-gazebo: &yarp-gazebo
  image: icubteamcode/superbuild-gazebo:v2021.11.1_master_sources
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "${HOME}/${APPSAWAY_APP_PATH_NOT_CONSOLE}/key_folder:/root/authorization"
    - "/dev:/dev"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true


services:
#following service are configured in icub-main/app/iCubStartup/scripts/iCubStartup.xml.template
  yBlender:
    <<: *yarp-blender
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; blender --python-use-system-env"


  yGazebo:
    <<: *yarp-gazebo
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; gazebo"





