version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/superbuild:v2020.05_binaries
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/root/.Xauthority:rw"
    - "${YARP_CONF_PATH}:/root/.config/yarp"
  networks:
    - hostnet

services:
    
    yserver:
      <<: *yarp-base
      deploy:
        placement:
          constraints: [node.role == manager]
      command: yarpserver --write

    ydevice:
      <<: *yarp-base
      deploy:
        placement:
          constraints: [node.role == manager]
      command: yarpdev --device test_grabber --period 0.5 --width 640 --height 480
       #use network.peer ip address and port 8080 to see the containers status in browser (http://localhost:8080/)
    visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]

networks:
  hostnet:
    external: true
    name: host

