version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/superbuild:v2021.08.1-stable_master_sources
  environment:
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
  networks:
    - hostnet

services:

    yserver:
      <<: *yarp-base
      deploy:
        placement:
          constraints: [node.role == manager]
      command: sh -c "yarp where | grep 'is available at ip' > /dev/null ; if [ ! $$? -eq 0 ]; then yarpserver --read; fi"

    ydevice:
      <<: *yarp-base
      deploy:
        placement:
          constraints: [node.role == manager]
      command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; yarpdev --device fakeFrameGrabber --period 0.5 --width 640 --height 480"
       #use network.peer ip address and port 8080 to see the containers status in browser (http://localhost:8080/)
    visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]

networks:
  hostnet:
    external: true
    name: host

