version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/speech:master_master-unstable_sources
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
    - FILE_INPUT
    - LANGUAGE_SYNTHESIS_INPUT
    - VOICE_NAME_INPUT
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/root/.Xauthority:rw"
    - "${YARP_CONF_PATH}:/root/.config/yarp"
    - "${FILE_INPUT_PATH}:/root/authorization"
    - "/dev:/dev"
  network_mode: "host"
  privileged: true
  #ipc: host

services:
#following service are configured in icub-main/app/iCubStartup/scripts/iCubStartup.xml.template
  
  yDemoGoogleSynthesis:
    <<: *yarp-base
    devices: 
      - "/dev/snd:/dev/snd"
    deploy:
      placement:
        constraints: [node.labels.type != head]
    command: sh -c "googleSynthesis --language ${LANGUAGE_SYNTHESIS_INPUT} --voice ${VOICE_NAME_INPUT}"

  






