version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/speech:v2021.08.1-stable_master_sources
  environment:
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
    - FILE_INPUT
    - LANGUAGE_SYNTHESIS_INPUT
    - VOICE_NAME_INPUT
    - XDG_RUNTIME_DIR
  volumes:
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "${FILE_INPUT_PATH}:/root/authorization"
    - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    - "~/.config/pulse/cookie:/root/.config/pulse/cookie"
    - "/dev:/dev"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true
  #ipc: host

services:
#following service are configured in icub-main/app/iCubStartup/scripts/iCubStartup.xml.template
  
  yDemoGoogleSynthesis:
    <<: *yarp-base
    devices: 
      - "/dev/snd:/dev/snd"
    deploy:
      placement:
        constraints: [node.labels.type != head]
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; googleSynthesis --language ${LANGUAGE_SYNTHESIS_INPUT} --voice ${VOICE_NAME_INPUT}"

  






