version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/human-sensing:v2022.02.0_sources
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true


services:

  ylogger:
    <<: *yarp-base
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; yarplogger --start"

#following services are configured in ./icub-main/app/default/scripts/cameras_calib.xml.template
  yview_pose:
    <<: *yarp-base
    command: sh -c "if [ ${YOP_INPUT} = 'True' ]; then yarp wait /yarpOpenPose/image:o ; yarpview --name /pose --x 340 --y 0 --p 50 --w 320 --h 240 ; fi"

  face:
    <<: *yarp-base
    command: sh -c "if [ ${FL_INPUT} = 'True' ]; then yarp wait /faceLandmarks/image:o ; yarpview --name /face --x 0 --y 0 --p 50 --w 320 --h 240 ; fi"

  yview_image:
    <<: *yarp-base
    command: sh -c "if [ ! -z ${CUSTOM_PORT} ]; then yarp wait ${CUSTOM_PORT}; else yarp wait /icub/camcalib/left/out; fi; yarpview --name /view/input_image --x 720 --y 0 --p 50 --w 320 --h 240"



