version: "3.7"

x-yarp-head: &yarp-head
  image: valegagge/superbuildmesaicubhead:latest
  environment:
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - type: volume
      source: mystack_yarp-config
      target: /root/.config/yarp
      volume:
        nocopy: true
    - "/dev:/dev"
  network_mode: "host"
  privileged: true


services:

  yrobotinterface:
    <<: *yarp-head
    devices: 
      - "/dev/bosch-i2c-imu:/dev/bosch-i2c-imu"
    container_name: yrobotinterface
    command: yarprobotinterface

  yGrabberCameras:
    <<: *yarp-head
    devices: 
      - "/dev/video0:/dev/video0"
    container_name: yGrabberCameras
    command: sh -c "yarpdev --from camera/ServerGrabberDualDragon.ini --split true"
    #command: sh -c "yarpdev --device usbCamera --d /dev/video0 --camModel leopard_python --name /icub/cam/left"

    #  yserialDevice4Emotions:
    #    <<: *yarp-head
    #    deploy:
    #      placement:
    #        constraints: [node.labels.type == head]
    #    command: sh -c "yarpdev --name /icub/face/raw --device serial --subdevice serialport --context faceExpressions --from serialport.ini"


volumes:
  mystack_yarp-config:
    external: true
