version: "3.7"

x-yarp-head: &yarp-head
  image: icubteamcode/superbuild-icubhead:master-unstable_binaries
  environment:
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "${YARP_CONF_PATH}:/root/.config/yarp"
    - "/dev:/dev"
  network_mode: "host"
  privileged: true


services:

  yGrabberCameras:
    <<: *yarp-head
    devices: 
      - "/dev/video0:/dev/video0"
    container_name: yGrabberCameras
    command: sh -c "if ! set|grep '^CUSTOM_PORT=' >/dev/null; then yarpdev --from camera/ServerGrabberDualDragon.ini --split true; fi"
    #command: sh -c "yarpdev --device usbCamera --d /dev/video0 --camModel leopard_python --name /icub/cam/left"

    #  yserialDevice4Emotions:
    #    <<: *yarp-head
    #    deploy:
    #      placement:
    #        constraints: [node.labels.type == head]
    #    command: sh -c "yarpdev --name /icub/face/raw --device serial --subdevice serialport --context faceExpressions --from serialport.ini"



