version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/camera_pan_calib:master_master-unstable_sources
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/root/.Xauthority:rw"
    - "${YARP_CONF_PATH}:/root/.config/yarp"
    - "/dev:/dev"
  network_mode: "host"
  privileged: true



services:
  
  yGrabberCameras:
    <<: *yarp-base
    devices: 
      - "/dev/video0:/dev/video0"
    container_name: yGrabberCameras
    command: sh -c "if [ -z ${LEFT_CUSTOM_PORT} && -z ${RIGHT_CUSTOM_PORT} ]; then yarpdev --from camera/ServerGrabberDualDragon.ini --split true; fi"  
 #------------------------------------------------------------------------------------------------
  #Calling CameraPanCalibration module 
  
  yDemoCameraPanCalibration:
    <<: *yarp-base
    command: sh -c "CameraPanCalibration" 
 
#------------------------------------------------------------------------------------------------
  #Opening the viewer to see the left output image
  yview_right_img_o:
    <<: *yarp-base
    container_name: yview_output_l
    command: yarpview --name /leftImageOutput

  #Opening we open the viewer to see the right output image
  yview_left_img_o:
    <<: *yarp-base
    container_name: yview_output_r
    command: yarpview --name /rightImageOutput

  #Opening we open the viewer to see left icub view
  yview_icub_l:
    <<: *yarp-base
    container_name: yview_icub_l
    command: sh -c "if [ -z ${LEFT_CUSTOM_PORT} && -z ${RIGHT_CUSTOM_PORT}]; then yarpview --name  /icub/view/left; fi"

  #Opening we open the viewer to see right icub view
  yview_icub_r:
    <<: *yarp-base
    container_name: yview_icub_r
    command: sh -c "if [ -z ${LEFT_CUSTOM_PORT} && -z ${RIGHT_CUSTOM_PORT}]; then yarpview --name  /icub/view/right; fi"

  #Opening we open the viewer to see the input of the right custom port
  yview_right_image_i:
    <<: *yarp-base
    container_name: yview_input_r
    command: yarpview --name /rightImageInput

  #Opening we open the viewer to see the input of the left custom port
  yview_left_image_i:
    <<: *yarp-base
    container_name: yview_input_l
    command: yarpview --name /leftImageInput












