- name: Prepare local registry
  hosts: nodes
  become: yes
  tasks:      
    - name: Update packages
      shell: apt-get update
      ignore_errors: yes
      when: ansible_distribution != 'MacOSX'

    - name: Install jq
      apt: 
        name:
          - jq
        state: latest
        autoclean: yes
      when: ansible_distribution != 'MacOSX'

    - name: Initialize JSON structure
      shell: |
        if [ -s /etc/docker/daemon.json ]
        then
          echo "File is not empty"
        else
          echo "{}" > /etc/docker/daemon.json
        fi
      args:
        warn: no
      when: ansible_distribution != 'MacOSX'

    - name: Adding local registry
      shell: |
        _registry={{ ansible_console_host }}:5000
        _has_insecure_registry=$( cat /etc/docker/daemon.json | grep "insecure-registries" )
        if [$_has_insecure_registry != ""]
        then
          _has_registry=$(cat /etc/docker/daemon.json | grep $_registry )
          if [$_has_registry == ""]
          then
            jq --arg registry "$_registry" '."insecure-registries"[."insecure-registries"| length] |= . + $registry' /etc/docker/daemon.json > daemon_new.txt
            mv daemon_new.txt /etc/docker/daemon.json
            echo "edited registries"
           fi
        else
          jq --arg registry $_registry '. += {"insecure-registries": [$registry] }' /etc/docker/daemon.json > daemon_new.txt
          mv daemon_new.txt /etc/docker/daemon.json
          echo "added registries"
        fi
      args:
        warn: no
      when: ansible_distribution != 'MacOSX'

