- name: Prepare Daemon 
  hosts: nodes
  become: yes
  tasks:      
    - name: Stop docker
      shell: sudo systemctl stop docker
      args:
        warn: no
      when: ansible_distribution != 'MacOSX'

    - name: Start docker
      shell: sudo systemctl start docker
      retries: 3
      delay: 30
      register: result
      until: result.rc == 0
      args:
        warn: no
      when: ansible_distribution != 'MacOSX'
