version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/superbuild:master-unstable_sources
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/root/.Xauthority:rw"
    - "${YARP_CONF_PATH}:/root/.config/yarp"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true
  #ipc: host


services:

  ylogger:
    <<: *yarp-base
    command: yarplogger --start

#following services are configured in ./icub-main/app/default/scripts/cameras_calib.xml.template
  yview_l:
    <<: *yarp-base
    command: sh -c "yarpview --name /icub/view/left --x 0 --y 0 --p 50"

  yview_r:
    <<: *yarp-base
    command: sh -c "yarpview --name /icub/view/right --x 450 --y 0 --p 50"

  yconnect_l:
    <<: *yarp-base
    depends_on:
      - yview
    command: sh -c "yarp wait /icub/camcalib/left/out; yarp wait /icub/view/left; yarp connect /icub/camcalib/left/out /icub/view/left udp"
    restart: on-failure

  yconnect_r:
    <<: *yarp-base
    depends_on:
      - yview
    command: sh -c "yarp wait /icub/camcalib/right/out; yarp wait /icub/view/right; yarp connect /icub/camcalib/right/out /icub/view/right udp"
    restart: on-failure

  yframeGrabberGui_l:
    <<: *yarp-base
    command: sh -c "yarp wait /icub/cam/left; frameGrabberGui2 --local /icub/fggui/left --remote /icub/cam/left --x 800 --y 0 --width 350 --height 500"


    
    
#-----------------------------------------------------------------------------------------------------------------------------------------------------
#Following services are configured in icub-basic-demos/demoRedBall/app/scripts/demoRedBall.xml.template 
  yview:
    <<: *yarp-base
    command: sh -c "yarpview --name /faceDetector_viewer --x 450 --y 400 --p 50"

  yconnect_demo:
    <<: *yarp-base
    depends_on:
      - yview
    command: sh -c "yarp wait /yarpOpenFace/outputImg:o; yarp wait /faceDetector_viewer; yarp connect /yarpOpenFace/outputImg:o /faceDetector_viewer udp"
    restart: on-failure


