version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/funny-things:v2021.08.1-stable_master_sources
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "/dev:/dev"
    - "${FILE_IMPORT_EXPORT_PATH:-/tmp/empty-dir}:/root/shared-files:rw"
  network_mode: "host"
  privileged: true

x-yarp-speech: &yarp-speech
  image: icubteamcode/speech:v2021.08.1-stable_master_sources
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
    - FILE_INPUT
    - LANGUAGE_SYNTHESIS_INPUT
    - VOICE_NAME_INPUT
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "${FILE_INPUT_PATH}:/root/authorization"
    - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    - "~/.config/pulse/cookie:/root/.config/pulse/cookie"
    - "/dev:/dev"
  network_mode: "host"
  privileged: true

services:
  yFunnyThingsApp:
    <<: *yarp-base
    command: sh -c "yarp wait /ctpservice/left_arm/rpc; yarp wait /ctpservice/right_arm/rpc; yarp wait /ctpservice/head/rpc; yarp wait /googleSynthesis/text:i; funnyThingsApp.AppImage --no-sandbox"

  yDemoGoogleSynthesis:
    <<: *yarp-speech
    devices: 
      - "/dev/snd:/dev/snd"
    deploy:
      placement:
        constraints: [node.labels.type != head]
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; googleSynthesis --language ${LANGUAGE_SYNTHESIS_INPUT} --voice ${VOICE_NAME_INPUT} --speed 0.93 --pitch -3.60"

  
