# this workflow will generate the containers on release, generating stable versions of the containers. The tag is given by:
#            - name: Get the version
#              id: get_version
#              run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
#              ${{ steps.get_version.outputs.VERSION }}

name: GTB_builder_release

on: 
    repository_dispatch:
        types: [GTB_build_stable]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: icub-tech-iit/code
                  token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}

            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

############## build the unstable version of graspTheBall ##############
            - name: Build graspTheBall Docker full image
              run: docker build --build-arg ${{ github.event.client_payload.superbuild_image_full }} --build-arg ${{ github.event.client_payload.superbuild_image_thin }} ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.grasptheball_tag_full }}
            - name: Push graspTheBall Docker full image
              run: docker push ${{ github.event.client_payload.grasptheball_tag_full }}

############## build the unstable version of graspTheBall ##############
            - name: Build graspTheBall Docker thin image
              run: docker build --build-arg ${{ github.event.client_payload.start_image_full }} --build-arg ${{ github.event.client_payload.superbuild_image_thin }} ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile4Production --tag ${{ github.event.client_payload.grasptheball_tag_thin }}
            - name: Push graspTheBall Docker thin image
              run: docker push ${{ github.event.client_payload.grasptheball_tag_thin }}

