# this workflow will generate the containers on push. These containers are for test only, so ideally they should be uploaded to a private repo, not available to the public. tag=superbuild_devel (?)
# for the stable versions, use superbuild_builder_stable.yml, triggered on release

name: GRGZ_onCodeChanges

on: 
    repository_dispatch:
        types: [GRGZ_onCodeChanges,GRGZ_onSBRelease]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: icub-tech-iit/code
                  token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}

            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


######## Command to build the full Docker image, using only unstable tag #########
            - name: Build superbuild Docker full image
              run: docker build ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.graspgazebo_unst_src }}
#########################################################################################

######### Command to push the full Docker Image online ##################################
            - name: Push superbuild Docker full image
              run: docker push ${{ github.event.client_payload.graspgazebo_unst_src }}
#########################################################################################

######## Command to build the thin Docker image, using only unstable tag #########
            - name: Build superbuild Docker thin image
              run: docker build --build-arg ${{ github.event.client_payload.unst_base_image_for_GRGZ_bin }} --build-arg ${{ github.event.client_payload.unst_base_image_for_GRGZ_src }} ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile4production --tag ${{ github.event.client_payload.graspgazebo_unst_bin}}
#########################################################################################

######### Command to push the thin Docker Image online ##################################
            - name: Push superbuild Docker thin image
              run: docker push ${{ github.event.client_payload.graspgazebo_unst_bin}}
#########################################################################################
