# this workflow will generate the containers on code release. These containers are for test only, so ideally they should be uploaded to a private repo, not available to the public. tag=superbuild-icubhead_devel (?)
# for the stable versions, use superbuild_icubHead_builder_stable.yml, triggered on release

name: SB_IH_onCodeRelease

on: 
    repository_dispatch:
        types: [SB_IH_onCodeRelease]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: icub-tech-iit/code
                  token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            - name: Check AppsAway version
              run: if [ "${{ github.event.client_payload.type }}" == "AppsAway_update" ]; then echo '${{ github.event.client_payload.version }}'; fi







##################### Command to set the tag for the date argument ######################
            - name: set date argument for Docker build
              run: |
                echo "$(date +'%d/%m/%Y')" > DATE_
                echo "metadata=$(cat DATE_)" > DATE_TAG
                echo $(cat DATE_TAG)
#########################################################################################

#########################################################################################
## THIS IS THE IMPLEMENTATION WITH STABLE/UNSTABLE VERSION (JUST TESTING UNSTABLE NOW) ##
#########################################################################################

########### This command sets the stable/unstable variable ##############################
            - name: set stable/unstable argument for Docker build
              run: |
                echo "Unstable" > SBTAG
                echo "sbtag=$(cat SBTAG)" > SBTAG_ARG
                echo $(cat SBTAG_ARG)
#########################################################################################

######## This command sets the release version (not used for the unstable version) ######            
#            - name: set release argument for Docker build
#              run: |
#                echo "release=$(cat VERSION_FILE)" > RELEASE_ARG
#                echo $(cat RELEASE_ARG)
#########################################################################################

######## Command to build the full Docker image, using only stable/unstable tag #########
            - name: Build superbuild-icubhead Docker full image
              run: docker build --build-arg $(cat DATE_TAG) --build-arg $(cat SBTAG_ARG)  ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.superbuild_icubhead_src }}
#########################################################################################

######### Command to push the full Docker Image online ##################################
            - name: Push superbuild-icubhead Docker full image
              run: docker push ${{ github.event.client_payload.superbuild_icubhead_src }}
#########################################################################################

######## Command to build the thin Docker image, using only stable/unstable tag #########
            - name: Build superbuild-icubhead Docker thin image
              run: docker build  --build-arg ${{ github.event.client_payload.base_image_for_SB_IH_bin }}  ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile4Production --tag ${{ github.event.client_payload.superbuild_icubhead_bin }}
#########################################################################################

######### Command to push the full Docker Image online ##################################
            - name: Push superbuild-icubhead Docker thin image
              run: docker push ${{ github.event.client_payload.superbuild_icubhead_bin }}

