# this workflow will generate the containers on push. These containers are for test only, so ideally they should be uploaded to a private repo, not available to the public. tag=superbuild_devel (?)
# for the stable versions, use superbuild_builder_stable.yml, triggered on release

name: SB_onCodeChanges

on: 
    repository_dispatch:
        types: [SB_onSBRelease]

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: icub-tech-iit/code
                  token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

##################### Command to set the tag for the date argument ######################
            - name: set date argument for Docker build
              run: |
                echo "$(date +'%d/%m/%Y')" > DATE_
                echo "metadata=$(cat DATE_)" > DATE_TAG
                echo $(cat DATE_TAG)
#########################################################################################

#########################################################################################
################### THIS IS THE IMPLEMENTATION WITH UNSTABLE VERSION ####################
#########################################################################################

########### This command sets the stable/unstable variable ##############################
            - name: set stable/unstable argument for Docker build
              run: |
                echo "Unstable" > SBTAG
                echo "sbtag=$(cat SBTAG)" > SBTAG_ARG
                echo $(cat SBTAG_ARG)
#########################################################################################

########### This command sets the master/release variable ##############################
            - name: set release/master argument for Docker build
              run: |
                echo ${{ github.event.client_payload.version }} > RELEASE_TAG
                echo "release=$(cat RELEASE_TAG)" > RELEASE_ARG
                echo $(cat RELEASE_ARG)
#########################################################################################

######## Command to build the full Docker image, using only unstable tag #########
            - name: Build superbuild Docker unstable full image
              run: docker build --build-arg ${{ github.event.client_payload.base_image_for_SB_src }} --build-arg $(cat DATE_TAG) --build-arg $(cat SBTAG_ARG) --build-arg $(cat RELEASE_ARG) ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.superbuild_unst_src }}
#########################################################################################

######### Command to push the full unstable Docker Image online ##################################
            - name: Push superbuild Docker unstable full image
              run: docker push ${{ github.event.client_payload.superbuild_unst_src }}
#########################################################################################

######## Command to build the thin Docker image, using only unstable tag #########
            - name: Build superbuild Docker unstable thin image
              run: docker build  --build-arg ${{ github.event.client_payload.unst_base_image_for_SB_bin }} --build-arg ${{ github.event.client_payload.base_image_for_SB_src }} ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile4Production --tag ${{ github.event.client_payload.superbuild_unst_bin }}
#########################################################################################

######### Command to push the thin unstable Docker Image online ##################################
            - name: Push superbuild Docker unstable thin image
              run: docker push ${{ github.event.client_payload.superbuild_unst_bin }}
#########################################################################################

    job_2:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: icub-tech-iit/code
                  token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

##################### Command to set the tag for the date argument ######################
            - name: set date argument for Docker build
              run: |
                echo "$(date +'%d/%m/%Y')" > DATE_
                echo "metadata=$(cat DATE_)" > DATE_TAG
                echo $(cat DATE_TAG)
#########################################################################################

#########################################################################################
##################### THIS IS THE IMPLEMENTATION WITH STABLE VERSION ####################
#########################################################################################

########### This command sets the master/release variable ##############################
            - name: set release/master argument for Docker build
              run: |
                echo ${{ github.event.client_payload.version }} > RELEASE_TAG
                echo "release=$(cat RELEASE_TAG)" > RELEASE_ARG
                echo $(cat RELEASE_ARG)
#########################################################################################

######## Command to build the full Docker image, using only stable tag #########
            - name: Build superbuild Docker stable full image
              run: docker build --build-arg ${{ github.event.client_payload.base_image_for_SB_src }} --build-arg $(cat DATE_TAG) --build-arg $(cat RELEASE_ARG) ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.superbuild_stab_src }}
#########################################################################################

######### Command to push the full stable Docker Image online ##################################
            - name: Push superbuild Docker stable full image
              run: docker push ${{ github.event.client_payload.superbuild_stab_src }}
#########################################################################################

######## Command to build the thin Docker image, using only stable tag #########
            - name: Build superbuild Docker stable thin image
              run: docker build  --build-arg ${{ github.event.client_payload.stab_base_image_for_SB_bin }} --build-arg ${{ github.event.client_payload.base_image_for_SB_src }} ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile4Production --tag ${{ github.event.client_payload.superbuild_stab_bin }}
#########################################################################################

######### Command to push the thin stable Docker Image online ##################################
            - name: Push superbuild Docker stable thin image
              run: docker push ${{ github.event.client_payload.superbuild_stab_bin }}
#########################################################################################

    job_3:
        needs: [job_1, job_2]
        runs-on: ubuntu-latest
        steps:
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
                repository: icub-tech-iit/appsAway
                event-type: G_S_onSBRelease
                client-payload: '{"version": "${{ github.event.client_payload.version }}", "type": "G_S_onSBRelease", 
                  "speech_unst_src": "icubteamcode/speech:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "speech_unst_bin": "icubteamcode/speech:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "unst_base_image_for_G_S_bin": "START_IMAGE_FULL_NAME=icubteamcode/speech:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "unst_sb_base_image_for_G_S_bin": "START_IMAGE_THIN_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "unst_base_image_for_G_S_src": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "docker_path": "./dockerfile_images/demos/speech"}'
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
                repository: icub-tech-iit/appsAway
                event-type: GTB_onSBRelease
                client-payload: '{"version": "${{ github.event.client_payload.version }}", "type": "GTB_onSBRelease", 
                  "extra_payload": {
                    "grasptheball_unst_src": "icubteamcode/grasptheball:${{ github.event.client_payload.version }}_master-unstable_sources", 
                    "grasptheball_unst_bin": "icubteamcode/grasptheball:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                    "grasptheball_stab_src": "icubteamcode/grasptheball:${{ github.event.client_payload.version }}_master-stable_sources", 
                    "grasptheball_stab_bin": "icubteamcode/grasptheball:${{ github.event.client_payload.version }}_master-stable_binaries", 
                    "unst_base_image_for_GTB_src": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_sources", 
                    "stab_base_image_for_GTB_src": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-stable_sources", 
                    "unst_sb_base_image_for_GTB_bin": "SUPERBUILD_THIN_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                    "stab_sb_base_image_for_GTB_bin": "SUPERBUILD_THIN_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-stable_binaries", 
                    "unst_base_image_for_GTB_bin": "START_IMAGE_FULL=icubteamcode/grasptheball:${{ github.event.client_payload.version }}_master-unstable_sources",            
                    "stab_base_image_for_GTB_bin": "START_IMAGE_FULL=icubteamcode/grasptheball:${{ github.event.client_payload.version }}_master-stable_sources",
                    "docker_path": "./dockerfile_images/demos/graspTheBall"}}'
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
                repository: icub-tech-iit/appsAway
                event-type: G_V_onSBRelease
                client-payload: '{"version": "${{ github.event.client_payload.version }}", "type": "G_V_onSBRelease", 
                  "googlevision_unst_src": "icubteamcode/googlevision:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "googlevision_unst_bin": "icubteamcode/googlevision:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "unst_base_image_for_G_V_bin": "START_IMAGE_FULL_NAME=icubteamcode/googlevision:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "unst_sb_base_image_for_G_V_bin": "START_IMAGE_THIN_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "unst_base_image_for_G_V_src": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "docker_path": "./dockerfile_images/demos/googleVisionAI"}'
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
                repository: icub-tech-iit/appsAway
                event-type: PAN_CALIB_onSBRelease
                client-payload: '{"version": "${{ github.event.client_payload.version }}", "type": "PAN_CALIB_onSBRelease", 
                  "pancalib_unst_src": "icubteamcode/camera_pan_calib:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "pancalib_unst_bin": "icubteamcode/camera_pan_calib:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "unst_base_image_for_PAN_CALIB_bin": "START_IMAGE_FULL_NAME=icubteamcode/camera_pan_calib:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "unst_sb_base_image_for_PAN_CALIB_bin": "START_IMAGE_THIN_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "unst_base_image_for_PAN_CALIB_src": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "docker_path": "./dockerfile_images/demos/cameraPanCalib"}'
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
                repository: icub-tech-iit/appsAway
                event-type: SBPyT_onSBRelease
                client-payload: '{"version": "${{ github.event.client_payload.version }}", "type": "SBPyT_onSBRelease", 
                  "superbuild_unst_src": "icubteamcode/superbuild-pytorch:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "superbuild_unst_bin": "icubteamcode/superbuild-pytorch:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "superbuild_stab_src": "icubteamcode/superbuild-pytorch:${{ github.event.client_payload.version }}_master-stable_sources", 
                  "superbuild_stab_bin": "icubteamcode/superbuild-pytorch:${{ github.event.client_payload.version }}_master-stable_binaries", 
                  "unst_base_image_for_SB_bin": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "stab_base_image_for_SB_bin": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-stable_sources", 
                  "base_image_for_SB_src": "BASE_IMG_NAME=pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime", 
                  "docker_path": "./dockerfile_images/basic/superbuild-pytorch"}'
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
                repository: icub-tech-iit/appsAway
                event-type: SBTF_onSBRelease
                client-payload: '{"version": "${{ github.event.client_payload.version }}", "type": "SBTF_onSBRelease", 
                  "superbuild_unst_src": "icubteamcode/superbuild-tensorflow-cpu:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "superbuild_unst_bin": "icubteamcode/superbuild-tensorflow-cpu:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "superbuild_stab_src": "icubteamcode/superbuild-tensorflow-cpu:${{ github.event.client_payload.version }}_master-stable_sources", 
                  "superbuild_stab_bin": "icubteamcode/superbuild-tensorflow-cpu:${{ github.event.client_payload.version }}_master-stable_binaries", 
                  "unst_base_image_for_SB_bin": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "stab_base_image_for_SB_bin": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-stable_sources", 
                  "base_image_for_SB_src": "BASE_IMG_NAME=tensorflow/tensorflow:latest", 
                  "docker_path": "./dockerfile_images/basic/superbuild-tensorflow"}'
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
                repository: icub-tech-iit/appsAway
                event-type: SBTF_onSBRelease
                client-payload: '{"version": "${{ github.event.client_payload.version }}", "type": "SBTF_onSBRelease", 
                  "superbuild_unst_src": "icubteamcode/superbuild-tensorflow-gpu:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "superbuild_unst_bin": "icubteamcode/superbuild-tensorflow-gpu:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                  "superbuild_stab_src": "icubteamcode/superbuild-tensorflow-gpu:${{ github.event.client_payload.version }}_master-stable_sources", 
                  "superbuild_stab_bin": "icubteamcode/superbuild-tensorflow-gpu:${{ github.event.client_payload.version }}_master-stable_binaries", 
                  "unst_base_image_for_SB_bin": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_sources", 
                  "stab_base_image_for_SB_bin": "SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-stable_sources", 
                  "base_image_for_SB_src": "BASE_IMG_NAME=tensorflow/tensorflow:latest-gpu", 
                  "docker_path": "./dockerfile_images/basic/superbuild-tensorflow"}'
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
                repository: icub-tech-iit/appsAway
                event-type: YOF_onSBRelease
                client-payload: '{"version": "${{ steps.get_version.outputs.VERSION }}", "type": "YOF_onSBRelease", 
                  "extra_payload": { 
                    "yarpopenface_unst_src": "icubteamcode/yarpopenface:${{ github.event.client_payload.version }}_master-unstable_sources", 
                    "yarpopenface_stab_src": "icubteamcode/yarpopenface:${{ github.event.client_payload.version }}_master-stable_sources", 
                    "yarpopenface_unst_bin": "icubteamcode/yarpopenface:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                    "yarpopenface_stab_bin": "icubteamcode/yarpopenface:${{ github.event.client_payload.version }}_master-stable_binaries", 
                    "unst_sb_base_image_for_YOF_src":"SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_sources", 
                    "stab_sb_base_image_for_YOF_src":"SUPERBUILD_FULL_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-stable_sources", 
                    "unst_sb_base_image_for_YOF_bin":"SUPERBUILD_THIN_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-unstable_binaries", 
                    "stab_sb_base_image_for_YOF_bin":"SUPERBUILD_THIN_NAME=icubteamcode/superbuild:${{ github.event.client_payload.version }}_master-stable_binaries", 
                    "unst_base_image_for_YOF_bin":"START_IMAGE_FULL_NAME=icubteamcode/yarpopenface:${{ github.event.client_payload.version }}_master-unstable_sources", 
                    "stab_base_image_for_YOF_bin":"START_IMAGE_FULL_NAME=icubteamcode/yarpopenface:${{ github.event.client_payload.version }}_master-stable_sources", 
                    "docker_path": "./dockerfile_images/demos/openFace"}}'

