name: Triggering app test

on:
  pull_request:
     types: [opened]
     branches:
        - master 
jobs:
    test:
      runs-on: ubuntu-latest
      steps:     
      - name: test
        run: echo ${{ github.event }}
