name: Triggering app test

on:
  push:
  pull_request:
     branches:
        - add_app*
jobs:
    test:
      runs-on: ubuntu-latest
      steps:     
      - name: test
        run: echo "This is a test"
