name: Triggering app test

on:
  pull_request:
     types: [opened, synchronize, reopened, edited]
     branches:
        - master 
jobs:
    test:
      runs-on: ubuntu-latest
      steps:     
      - name: test
        run:  echo " ${{ toJson(github.event) }}"
