name: Triggering app test

on:
  push:
  pull_request_target:
    types: [opened]
    branches:
      - 'master'
 jobs:
    test:
      runs-on: ubuntu-latest
      steps:     
      - name: test
        run: echo "This is a test"
