on:
  pull_request:
    types: [closed]


#            mv -v ./appsAway/user_changes/* ./icub-tech-apps/dist/database/upgrade/
#            mv -v ./appsAway/user_changes/images/* ./icub-tech-apps/dist/express/images/

jobs:
  update_code:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'user_changes')
    steps: 
      # we checkout appsAway code
      - uses: actions/checkout@v2

      - name: copies user_changes to temporary folder
        run: |
            git clone https://github.com/icub-tech-iit/appsAway
            mkdir -p ../test/
            mv -v ./user_changes/*.json ../test/
            mv -v ./user_changes/images/*.png ../test/
            mv -v ./user_changes/images/*.jpg ../test/
            mv -v ./user_changes/images/*.jpeg ../test/
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "removing user_changes from appsAway" -a

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: remove appsAway
        run: |
            cd ..
            rm -rf ./appsAway

      - uses: actions/checkout@v2
        with:
            repository: icub-tech-iit/code
            token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}

      - name: copies user_changes folder
        run: |
            mkdir -p test/
            mv -v ../test/* ./test/

      - name: Commit changes
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Merged user changes in code" -a
        
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: placeholder job
        run: |
            echo "${{ toJson(github.event.pull_request) }}"
            echo "${{ contains(github.event.pull_request.head.ref, 'user_changes') }}"
            echo "${{ contains(github.event.pull_request.head.ref, 'user_changes*') }}"
