name: user_input_PR


on:
  push:
      branches:
          - 'user_changes*'


jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: get usernames
      id: get_usernames
      run: |
            cd user_changes
            file_list=$(ls -p | grep -v / )
            len_list=${#file_list[@]}
            iter=0
            for file in $file_list
            do
              if [ $iter != 0 ];
              then
                user_list="$user_list,"
              fi
              user_list="$user_list$(head -1 $file | awk -F'//' '{print $2}')"
              iter=$((iter+1))
            done
            echo $user_list
            echo ::set-output name=user_list::$user_list

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        pr_title: "Adding user changes into the website."
        pr_assignee: ${{ steps.get_usernames.outputs.user_list }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
