name: user_input_PR


on:
  push:
    paths: 'user_changes/**'
    branches:
          - 'user_changes*'


jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: get file data
      id: get_filedata
      run: |
            cd user_changes
            file_list=$(ls -p | grep -v / )
            len_list=${#file_list[@]}
            iter=0
            for file in $file_list
            do
              if [ $iter != 0 ];
              then
                user_list="$user_list,"
                changes_list ="$changes_list\n\n"
              fi
              user_list="$user_list$(head -1 $file | awk -F'//' '{print $2}')"
              changes_list="$changes_list$(tail -n +1 $file | awk -F'//db' '{print $2}')"
              iter=$((iter+1))
            done
            echo $user_list
            echo $changes_list
            echo ::set-output name=user_list::$user_list
            echo ::set-output name=changes_list::$changes_list

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        pr_title: "Adding user changes into the website."
        pr_body: ${{ steps.get_filedata.outputs.changes_list }}
        pr_reviewer: "AlexAntn,vtikha,ilaria-carlini"
        pr_assignee: ${{ steps.get_filedata.outputs.user_list }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
