name: Webhook trigger for code repository

on:
  push:
    paths:
      - 'modules/**'

jobs:
    job_id: 
        runs-on: [ubuntu-latest]
        steps:
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
            repository: icub-tech-iit/code
            event-type: AppsAway_update
            client-payload: '{"version": "${{ steps.get_version.outputs.VERSION }}", "type": "AppsAway_update"}'
