# this workflow will generate the containers on push. These containers are for test only, so ideally they should be uploaded to a private repo, not available to the public. tag=yarpOpenFace:version (?)
# for the stable versions, use yarpOpenFace_builder_stable.yml, triggered on release

name: YOF_builder_devel

on: 
    repository_dispatch:
        types: [YOF_build]

jobs:
    build-unstable:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: icub-tech-iit/code
                  token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


############## build the unstable version of yarpOpenFace ##############
            - name: Build yarpOpenFace Docker full image
              run: docker build --build-arg ${{ github.event.client_payload.extra_payload.start_unstable_image_full }} --build-arg ${{ github.event.client_payload.extra_payload.start_unstable_image_thin }} ${{ github.event.client_payload.extra_payload.docker_path }} --file ${{ github.event.client_payload.extra_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.extra_payload.yarpOpenFace_unstable_tag_full }}
            - name: Push yarpOpenFace Docker full image
              run: docker push ${{ github.event.client_payload.extra_payload.yarpOpenFace_unstable_tag_full }}


            
############## build the unstable version of yarpOpenFace ##############
            - name: Build yarpOpenFace Docker thin image
              run: docker build --build-arg ${{ github.event.client_payload.extra_payload.start_yarpOpenFace_unstable_full }} --build-arg ${{ github.event.client_payload.extra_payload.start_unstable_image_thin }} ${{ github.event.client_payload.extra_payload.docker_path }}--file ${{ github.event.client_payload.extra_payload.docker_path }}/Dockerfile4Production --tag ${{ github.event.client_payload.extra_payload.yarpOpenFace_unstable_tag_thin }}
            - name: Push yarpOpenFace Docker thin image
              run: docker push ${{ github.event.client_payload.extra_payload.yarpOpenFace_unstable_tag_thin }}
              

############## build the stable version of yarpOpenFace ##############
            - name: Build yarpOpenFace Docker thin image
              run: docker build --build-arg ${{ github.event.client_payload.extra_payload.start_stable_image_full }} --build-arg ${{ github.event.client_payload.extra_payload.start_stable_image_thin }} ${{ github.event.client_payload.extra_payload.docker_path }} --file ${{ github.event.client_payload.extra_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.extra_payload.yarpOpenFace_stable_tag_full }}
            - name: Push yarpOpenFace Docker thin image
              run: docker push ${{ github.event.client_payload.extra_payload.yarpOpenFace_stable_tag_full }}

############## build the stable version of yarpOpenFace ##############
            - name: Build yarpOpenFace Docker thin image
              run: docker build --build-arg ${{ github.event.client_payload.extra_payload.start_yarpOpenFace_stable_full }} --build-arg ${{ github.event.client_payload.extra_payload.start_stable_image_thin }} ${{ github.event.client_payload.extra_payload.docker_path }}--file ${{ github.event.client_payload.extra_payload.docker_path }}/Dockerfile4Production --tag ${{ github.event.client_payload.extra_payload.yarpOpenFace_stable_tag_thin }}
            - name: Push yarpOpenFace Docker thin image
              run: docker push ${{ github.event.client_payload.extra_payload.yarpOpenFace_stable_tag_thin }}

